<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net462</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Description>A modding library designed for the game The Farmer Was Replaced</Description>
        <Authors>seadoggie</Authors>
        <Version>0.0.1</Version>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
        </RestoreAdditionalProjectSources>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    
    <!-- Import a settings file. See local.props.txt for more information -->
    <Import Project="local.props" Condition="Exists('local.props')" />
    
    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" PrivateAssets="all"  />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" PrivateAssets="all"  />
        <PackageReference Include="UnityEngine.Modules" Version="2021.3.5" PrivateAssets="all" />
        <Reference Include="$(ManagedPath)/Core.dll" Publicize="false" />
        <Reference Include="$(ManagedPath)/Utils.dll" Publicize="false" />
        <Reference Include="UnityEngine.UI">
            <HintPath>$(ManagedPath)\UnityEngine.UI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(ManagedPath)\Unity.TextMeshPro.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
