<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net46</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Description>A modding library designed for the game The Farmer Was Replaced</Description>
        <Authors>seadoggie</Authors>
        <Version>0.0.0</Version>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
        </RestoreAdditionalProjectSources>
    </PropertyGroup>
    
    <!-- Import a settings file. See local.props.txt for more information -->
    <Import Project="local.props" Condition="Exists('local.props')" />
    
    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
        <PackageReference Include="UnityEngine.Modules" Version="2021.3.5" IncludeAssets="compile" />
        <Reference Include="$(ManagedPath)/Core.dll" Publicize="true" />
        <Reference Include="$(ManagedPath)/Utils.dll" Publicize="true" />
        <Reference Include="UnityEngine.UI">
            <HintPath>$(ManagedPath)\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(ManagedPath)\Unity.TextMeshPro.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
